name: CI pipeline

on:
  push:
    branches:
      - master

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Tests
      run: npm install && npm test
    
    - name: Build Docker Image
      run: docker build -t bhumika140/my-cicd-app:${{github.sha}} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - name: Push Docker Image
      run: docker push bhumika140/my-cicd-app:${{github.sha}}

